version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:30"
      timezone: "Asia/Saigon"
    allow:
      - dependency-type: "direct"

  - package-ecosystem: "npm"
    directory: "/example"
    target-branch: "develop"
    schedule:
      interval: "monthly"