# note: having asignee doesn't automatically remove label, as an issue can have multiple assignees.

on:
  issues:
    types: [opened, unassigned]

jobs:
  check_and_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const assignees = context.payload.issue.assignees
            const current_label = context.payload.issue.labels

            if (assignees.length === 0){
              github.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.issue.number,
                labels: ["help wanted"]
            })
            }
