name: run Jest Tests
on:
  push:
    branches:
      - main
      - 'develop'
      - 'demo/try_github_actions'
      - 'releases/**'
    tag:
      - v1
      - v1.*

  pull_request:
    branches:
      - main
      - 'develop'
      - 'demo/try_github_actions'
      - 'releases/**'
    tag:
      - v1
      - v1.*

jobs:
  run_jest_tests_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependency
        run: echo hello